Module2 task1
htmlacademy-nodejs/1506063-buy-and-sell-3 pull request #3
Opened 2020-08-26 21:48 UTC by inchernobuk

2020-08-26 22:06 UTC, thadjbullet commented on src/service/cli/generate.js
> +    } catch {
Здесь ошибка в синтаксисе. Посмотри как записывается `try/catch`

2020-08-26 22:07 UTC, thadjbullet requested changes

2020-08-26 22:07 UTC, thadjbullet commented on src/service/cli/generate.js
> +    } catch {
Здесь ошибка в синтаксисе. Посмотри как записывается `try/catch`

2020-08-27 07:13 UTC, inchernobuk commented on src/service/cli/generate.js
> +    } catch (err) {
🤦‍♂️

2020-08-29 00:16 UTC, merged